const imageBaseURL = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";
const restaurantsData = [
  {
    type: "F",
    id: "533385",
    name: "KFC",
    uuid: "8a8634ed-6c6c-4539-9de1-0df978d7be3b",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "1000+ ratings",
    cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    tags: [],
    costForTwo: 40000,
    costForTwoString: "₹400 FOR TWO",
    deliveryTime: 30,
    minDeliveryTime: 30,
    maxDeliveryTime: 30,
    slaString: "30 MINS",
    lastMileTravel: 2.5999999046325684,
    slugs: {
      restaurant: "kfc-vaishali-vaishali-nagar",
      city: "jaipur",
    },
    cityState: "12",
    address: "SHOP 8,9,11, 11/A. VAISHALI TOWER2. NURSERY CIRCLE, VAISHALI NAGAR . JAIPUR, RAJASTHAN",
    locality: "Nursery Circle",
    parentId: 547,
    unserviceable: false,
    veg: false,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    ribbon: [
      {
        type: "PROMOTED",
      },
    ],
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2500,
          message: "",
        },
        {
          name: "time",
          fee: 0,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 2500,
      message: "",
      title: "Delivery Charge",
      amount: "2500",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "cid=6679859~p=1~eid=00000187-dce2-ae92-1eb0-b5c600890121",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "2.5 kms",
    hasSurge: false,
    sla: {
      restaurantId: "533385",
      deliveryTime: 30,
      minDeliveryTime: 30,
      maxDeliveryTime: 30,
      lastMileTravel: 2.5999999046325684,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: true,
    avgRating: "4.1",
    totalRatings: 1000,
    new: false,
  },
  {
    type: "F",
    id: "143098",
    name: "Rominus Pizza & Burger",
    uuid: "5d4c5fd1-d4f1-43c0-aeb3-d26b592b0672",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "5000+ ratings",
    cloudinaryImageId: "9ec9ffd900c24ef751e2f34ba3d2fd4b",
    cuisines: [
      "Pizzas",
      "American",
      "Barbecue",
      "Italian-American",
      "Snacks",
      "Grill",
      "Italian",
      "Pastas",
      "Sweets",
      "Desserts",
      "Beverages",
    ],
    tags: [],
    costForTwo: 20000,
    costForTwoString: "₹200 FOR TWO",
    deliveryTime: 29,
    minDeliveryTime: 29,
    maxDeliveryTime: 29,
    slaString: "29 MINS",
    lastMileTravel: 2.5999999046325684,
    slugs: {
      restaurant: "rominus-pizza-burger-khatipura-ajmer-road",
      city: "jaipur",
    },
    cityState: "12",
    address: "A 8  2nd Floor  Square 29 Building  Above HDFC Bank  Hanuman Nagar Vaishali Nagar  Jaipur",
    locality: "Hanuman Nagar",
    parentId: 8387,
    unserviceable: false,
    veg: false,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "Flat ₹125 off",
      shortDescriptionList: [
        {
          meta: "Flat ₹125 off on orders above ₹249",
          discountType: "Flat",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
          discountType: "Flat",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "₹125 OFF",
      shortDescriptionList: [
        {
          meta: "Use MATCHDEAL125",
          discountType: "Flat",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
          discountType: "Flat",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    ribbon: [
      {
        type: "PROMOTED",
      },
    ],
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "cid=6689835~p=13~eid=00000187-dd9b-b68a-2019-d70900e40d1c",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "2.5 kms",
    hasSurge: false,
    sla: {
      restaurantId: "143098",
      deliveryTime: 29,
      minDeliveryTime: 29,
      maxDeliveryTime: 29,
      lastMileTravel: 2.5999999046325684,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: true,
    avgRating: "3.6",
    totalRatings: 5000,
    new: false,
  },
  {
    type: "F",
    id: "62568",
    name: "Choudhary Dhaba Khatipura Mod",
    uuid: "200a22b5-9cf0-4797-8685-a13ea6bae14d",
    city: "12",
    area: "Khatipura Road",
    totalRatingsString: "10000+ ratings",
    cloudinaryImageId: "jopdgt9qeojd26rn0atj",
    cuisines: [
      "North Indian",
      "Thalis",
      "Chinese",
      "Mughlai",
      "Chaat",
      "Punjabi",
      "Desserts",
      "Snacks",
      "Rajasthani",
      "Tandoor",
      "Sweets",
      "Indian",
      "Beverages",
      "Ice Cream",
      "Italian",
      "Pastas",
    ],
    tags: [],
    costForTwo: 20000,
    costForTwoString: "₹200 FOR TWO",
    deliveryTime: 20,
    minDeliveryTime: 20,
    maxDeliveryTime: 20,
    slaString: "20 MINS",
    lastMileTravel: 2.5,
    slugs: {
      restaurant: "choudhary-dhaba-khatipura-road-vaishali-nagar",
      city: "jaipur",
    },
    cityState: "12",
    address: "4, Marudhar Vihar, Khatipura Road, Jaipur",
    locality: "Marudhar Vihar",
    parentId: 62813,
    unserviceable: false,
    veg: false,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "60% off",
      shortDescriptionList: [
        {
          meta: "60% off | Use MISSEDYOU",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹120 | Use code MISSEDYOU",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "60% OFF",
      shortDescriptionList: [
        {
          meta: "Use MISSEDYOU",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹120 | Use code MISSEDYOU",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "2.5 kms",
    hasSurge: false,
    sla: {
      restaurantId: "62568",
      deliveryTime: 20,
      minDeliveryTime: 20,
      maxDeliveryTime: 20,
      lastMileTravel: 2.5,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "3.9",
    totalRatings: 10000,
    new: false,
  },
  {
    type: "F",
    id: "90186",
    name: "Burger King",
    uuid: "ac633e0c-aa7c-4156-97d2-4cc70fcba4b2",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "10000+ ratings",
    cloudinaryImageId: "28fb13049b4e55297bb3f703cde63c35",
    cuisines: ["Burgers", "American"],
    tags: [],
    costForTwo: 35000,
    costForTwoString: "₹350 FOR TWO",
    deliveryTime: 26,
    minDeliveryTime: 26,
    maxDeliveryTime: 26,
    slaString: "26 MINS",
    lastMileTravel: 2.799999952316284,
    slugs: {
      restaurant: "burger-king-vaishali-nagar-vaishali-nagar",
      city: "jaipur",
    },
    cityState: "12",
    address: "Burger King India Pvt.Ltd.S-38, 39, 40, Matoria Plaza, GDA Central Market, Vaishali Nagar, Jaipur-302021",
    locality: "Amrapali Marg",
    parentId: 166,
    unserviceable: false,
    veg: false,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "40% off",
      shortDescriptionList: [
        {
          meta: "40% off | Use SPECIALS",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "40% off up to ₹80 on select items | Use code SPECIALS",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "40% OFF",
      shortDescriptionList: [
        {
          meta: "Use SPECIALS",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "40% off up to ₹80 on select items | Use code SPECIALS",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "2.7 kms",
    hasSurge: false,
    sla: {
      restaurantId: "90186",
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      lastMileTravel: 2.799999952316284,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "4.1",
    totalRatings: 10000,
    new: false,
  },
  {
    type: "F",
    id: "125850",
    name: "La Pino'z Pizza",
    uuid: "d3eef747-62aa-418a-823f-04e844bdab96",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "5000+ ratings",
    cloudinaryImageId: "y8xhvzf61t0zatbefstk",
    cuisines: ["Pizzas", "Italian", "Beverages", "Desserts"],
    tags: [],
    costForTwo: 40000,
    costForTwoString: "₹400 FOR TWO",
    deliveryTime: 25,
    minDeliveryTime: 25,
    maxDeliveryTime: 25,
    slaString: "25 MINS",
    lastMileTravel: 3,
    slugs: {
      restaurant: "la-pinoz-pizza-vaishali-nagar-amrapali-circle-vaishali-nagar",
      city: "jaipur",
    },
    cityState: "12",
    address: "G-18, Evershine Tower, Amrapali Circle, Vaishali Nagar, Jaipur",
    locality: "Evershine Tower",
    parentId: 4961,
    unserviceable: false,
    veg: false,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "Flat ₹125 off",
      shortDescriptionList: [
        {
          meta: "Flat ₹125 off on orders above ₹249",
          discountType: "Flat",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
          discountType: "Flat",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "₹125 OFF",
      shortDescriptionList: [
        {
          meta: "Use MATCHDEAL125",
          discountType: "Flat",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
          discountType: "Flat",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    ribbon: [
      {
        type: "PROMOTED",
      },
    ],
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 3600,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 6100,
      message: "",
      title: "Delivery Charge",
      amount: "6100",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "cid=6675165~p=7~eid=00000187-dd9b-b68a-2019-d70700e40748",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "3 kms",
    hasSurge: false,
    sla: {
      restaurantId: "125850",
      deliveryTime: 25,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      lastMileTravel: 3,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: true,
    avgRating: "3.7",
    totalRatings: 5000,
    new: false,
  },
  {
    type: "F",
    id: "653660",
    name: "Cake",
    uuid: "ab2071a9-df62-4716-b82f-65afdbb6d37f",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "50+ ratings",
    cloudinaryImageId: "28b95a24183105eafe5230e7896d32d5",
    cuisines: ["Bakery"],
    tags: [],
    costForTwo: 70000,
    costForTwoString: "₹700 FOR TWO",
    deliveryTime: 21,
    minDeliveryTime: 21,
    maxDeliveryTime: 21,
    slaString: "21 MINS",
    lastMileTravel: 0.5,
    slugs: {
      restaurant: "cake-vaishali-nagar-vaishali-nagar-4",
      city: "jaipur",
    },
    cityState: "12",
    address: "162 engineer colony near rajat hospital panchawala jaipur 302034",
    locality: "Sirsi Road",
    parentId: 3862,
    unserviceable: false,
    veg: false,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "60% off",
      shortDescriptionList: [
        {
          meta: "60% off | Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "60% OFF",
      shortDescriptionList: [
        {
          meta: "Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "0.5 kms",
    hasSurge: false,
    sla: {
      restaurantId: "653660",
      deliveryTime: 21,
      minDeliveryTime: 21,
      maxDeliveryTime: 21,
      lastMileTravel: 0.5,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "3.7",
    totalRatings: 50,
    new: false,
  },
  {
    type: "F",
    id: "668179",
    name: "Chikiii's Cake N Bake",
    uuid: "83236e20-094c-4178-9f68-3b2f8852caf2",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "Too Few Ratings",
    cloudinaryImageId: "24092d9db646efb22e9937b0c62dafac",
    cuisines: ["Bakery"],
    tags: [],
    costForTwo: 10000,
    costForTwoString: "₹100 FOR TWO",
    deliveryTime: 24,
    minDeliveryTime: 24,
    maxDeliveryTime: 24,
    slaString: "24 MINS",
    lastMileTravel: 0.4000000059604645,
    slugs: {
      restaurant: "chikiii's-cake-n-bake-vaishali-nagar-vaishali-nagar",
      city: "jaipur",
    },
    cityState: "12",
    address: "3, Jaswant Nagar, Kanakpura, Jaipur, Rajasthan 302012, India",
    locality: "Jaswant Nagar",
    parentId: 400650,
    unserviceable: false,
    veg: true,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "0.4 kms",
    hasSurge: false,
    sla: {
      restaurantId: "668179",
      deliveryTime: 24,
      minDeliveryTime: 24,
      maxDeliveryTime: 24,
      lastMileTravel: 0.4000000059604645,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "--",
    totalRatings: 0,
    new: false,
  },
  {
    type: "F",
    id: "58786",
    name: "Choudhary Annapurna Bhojanalaya",
    uuid: "b9026e31-88a8-44c2-987e-985a5f2668fd",
    city: "12",
    area: "Khatipura Road",
    totalRatingsString: "10000+ ratings",
    cloudinaryImageId: "rajgmo7t6mooimqhgn71",
    cuisines: [
      "North Indian",
      "Biryani",
      "Thalis",
      "Mughlai",
      "Snacks",
      "Kebabs",
      "Afghani",
      "Tandoor",
      "Indian",
      "Grill",
      "Hyderabadi",
      "Lucknowi",
    ],
    tags: [],
    costForTwo: 30000,
    costForTwoString: "₹300 FOR TWO",
    deliveryTime: 20,
    minDeliveryTime: 20,
    maxDeliveryTime: 20,
    slaString: "20 MINS",
    lastMileTravel: 2.5,
    slugs: {
      restaurant: "choudhary-annapurna-bhojanalaya-khatipura-road-vaishali-nagar",
      city: "jaipur",
    },
    cityState: "12",
    address: "4, Khatipura Road, Jaipur",
    locality: "Marudhar Vihar",
    parentId: 62806,
    unserviceable: false,
    veg: true,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "60% off",
      shortDescriptionList: [
        {
          meta: "60% off | Use MISSEDYOU",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹120 | Use code MISSEDYOU",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "60% OFF",
      shortDescriptionList: [
        {
          meta: "Use MISSEDYOU",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹120 | Use code MISSEDYOU",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "Closes soon",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "2.5 kms",
    hasSurge: false,
    sla: {
      restaurantId: "58786",
      deliveryTime: 20,
      minDeliveryTime: 20,
      maxDeliveryTime: 20,
      lastMileTravel: 2.5,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "3.9",
    totalRatings: 10000,
    new: false,
  },
  {
    type: "F",
    id: "631711",
    name: "Khandelwal Dhaba",
    uuid: "b086c4ae-4928-492d-881e-564b94ec2b4a",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "20+ ratings",
    cloudinaryImageId: "yiqu9fvbtljk2azevnpa",
    cuisines: ["North Indian", "Indian", "Beverages"],
    tags: [],
    costForTwo: 20000,
    costForTwoString: "₹200 FOR TWO",
    deliveryTime: 23,
    minDeliveryTime: 23,
    maxDeliveryTime: 23,
    slaString: "23 MINS",
    lastMileTravel: 0.800000011920929,
    slugs: {
      restaurant: "khandelwal-dhaba-vaishali-nagar-vaishali-nagar-4",
      city: "jaipur",
    },
    cityState: "12",
    address: "467A CHITRAKOOT , VAISHALI NAGAR  JAIPUR - 302021",
    locality: "Chitrakoot",
    parentId: 117386,
    unserviceable: false,
    veg: true,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "60% off",
      shortDescriptionList: [
        {
          meta: "60% off | Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "60% OFF",
      shortDescriptionList: [
        {
          meta: "Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "0.8 kms",
    hasSurge: false,
    sla: {
      restaurantId: "631711",
      deliveryTime: 23,
      minDeliveryTime: 23,
      maxDeliveryTime: 23,
      lastMileTravel: 0.800000011920929,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "3.3",
    totalRatings: 20,
    new: false,
  },
  {
    type: "F",
    id: "668687",
    name: "Fruit Hunter",
    uuid: "ca85687f-55a1-484e-97e0-ddc37c91cdc1",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "Too Few Ratings",
    cloudinaryImageId: "a14e846df41464eb561867be73f84ac0",
    cuisines: ["Bakery"],
    tags: [],
    costForTwo: 12000,
    costForTwoString: "₹120 FOR TWO",
    deliveryTime: 26,
    minDeliveryTime: 26,
    maxDeliveryTime: 26,
    slaString: "26 MINS",
    lastMileTravel: 0.4000000059604645,
    slugs: {
      restaurant: "fruit-hunter-vaishali-nagar-vaishali-nagar",
      city: "jaipur",
    },
    cityState: "12",
    address: "3, Jaswant Nagar, Kanakpura, Jaipur, Rajasthan 302012, India",
    locality: "Jaswant Nagar",
    parentId: 400943,
    unserviceable: false,
    veg: true,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "60% off",
      shortDescriptionList: [
        {
          meta: "60% off | Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "60% OFF",
      shortDescriptionList: [
        {
          meta: "Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "0.4 kms",
    hasSurge: false,
    sla: {
      restaurantId: "668687",
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      lastMileTravel: 0.4000000059604645,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "--",
    totalRatings: 0,
    new: false,
  },

  {
    type: "F",
    id: "669311",
    name: "Fantooshh Bakers",
    uuid: "d6bc77ed-b3e5-44dd-8ced-3fd493667721",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "Too Few Ratings",
    cloudinaryImageId: "60a8b98fc9d14de1acff6cad0731923b",
    cuisines: ["Bakery"],
    tags: [],
    costForTwo: 15000,
    costForTwoString: "₹150 FOR TWO",
    deliveryTime: 26,
    minDeliveryTime: 26,
    maxDeliveryTime: 26,
    slaString: "26 MINS",
    lastMileTravel: 0.4000000059604645,
    slugs: {
      restaurant: "fantooshh-bakers-vaishali-nagar-vaishali-nagar",
      city: "jaipur",
    },
    cityState: "12",
    address: "3, Jaswant Nagar, Kanakpura, Jaipur, Rajasthan 302012, India",
    locality: "Jaswant nagar",
    parentId: 401255,
    unserviceable: false,
    veg: true,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "60% off",
      shortDescriptionList: [
        {
          meta: "60% off | Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "60% OFF",
      shortDescriptionList: [
        {
          meta: "Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "0.4 kms",
    hasSurge: false,
    sla: {
      restaurantId: "669311",
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      lastMileTravel: 0.4000000059604645,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "--",
    totalRatings: 0,
    new: false,
  },

  {
    type: "F",
    id: "668321",
    name: "Kaka Cake",
    uuid: "d53772e7-9534-445c-8ba3-5aeb41b4ddc1",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "Too Few Ratings",
    cloudinaryImageId: "8fa5b0c8a1dd82a7faaa4251477a7ba0",
    cuisines: ["Bakery", "Indian"],
    tags: [],
    costForTwo: 10000,
    costForTwoString: "₹100 FOR TWO",
    deliveryTime: 26,
    minDeliveryTime: 26,
    maxDeliveryTime: 26,
    slaString: "26 MINS",
    lastMileTravel: 0.4000000059604645,
    slugs: {
      restaurant: "kaka-cake-vaishali-nagar-vaishali-nagar",
      city: "jaipur",
    },
    cityState: "12",
    address: "3, Jaswant Nagar, Kanakpura, Jaipur, Rajasthan 302012, India",
    locality: "Jaswant nagar",
    parentId: 400744,
    unserviceable: false,
    veg: true,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "60% off",
      shortDescriptionList: [
        {
          meta: "60% off | Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "60% OFF",
      shortDescriptionList: [
        {
          meta: "Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "0.4 kms",
    hasSurge: false,
    sla: {
      restaurantId: "668321",
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      lastMileTravel: 0.4000000059604645,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "--",
    totalRatings: 0,
    new: false,
  },

  {
    type: "F",
    id: "455136",
    name: "Cake King",
    uuid: "b9e4f66d-4a38-4d60-acea-11be32554f2e",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "Too Few Ratings",
    cloudinaryImageId: "58ca35f7a74cc2abeb0d538c3d7101ca",
    cuisines: ["Bakery"],
    tags: [],
    costForTwo: 65000,
    costForTwoString: "₹650 FOR TWO",
    deliveryTime: 26,
    minDeliveryTime: 26,
    maxDeliveryTime: 26,
    slaString: "26 MINS",
    lastMileTravel: 0.5,
    slugs: {
      restaurant: "cake-king-??-vaishali-nagar-vaishali-nagar",
      city: "jaipur",
    },
    cityState: "12",
    address: "162, Engineer Colony Pachawala , Jaipur, Jaipur, Rajasthan, 302034",
    locality: "Engineer Colony",
    parentId: 54937,
    unserviceable: false,
    veg: true,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "60% off",
      shortDescriptionList: [
        {
          meta: "60% off | Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "60% OFF",
      shortDescriptionList: [
        {
          meta: "Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "0.5 kms",
    hasSurge: false,
    sla: {
      restaurantId: "455136",
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      lastMileTravel: 0.5,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "--",
    totalRatings: 0,
    new: false,
  },

  {
    type: "F",
    id: "614874",
    name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
    uuid: "70c2bcf1-7201-4bca-b6cf-9ec8d02ea4ad",
    city: "12",
    area: "Manasarovar",
    totalRatingsString: "50+ ratings",
    cloudinaryImageId: "gt6dh26yrnp7frvs23eh",
    cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
    tags: [],
    costForTwo: 20000,
    costForTwoString: "₹200 FOR TWO",
    deliveryTime: 30,
    minDeliveryTime: 30,
    maxDeliveryTime: 30,
    slaString: "30 MINS",
    lastMileTravel: 8.100000381469727,
    slugs: {
      restaurant: "kwality-walls-frozen-dessert-and-ice-cream-shop-manasarovar-manasarovar-3",
      city: "jaipur",
    },
    cityState: "12",
    address:
      "GOVIND FARMS: PLOT NO. 3, KAMAL VIHAR, MANGYAWAS ROAD, MANSAROVAR, JAIPUR, Sanganer, Jaipur II, Rajasthan-302020 (HUL- I351079P2473)",
    locality: "Kamal Vihar",
    parentId: 582,
    unserviceable: false,
    veg: true,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    ribbon: [
      {
        type: "PROMOTED",
      },
    ],
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 8000,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 10500,
      message: "",
      title: "Delivery Charge",
      amount: "10500",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "Closes soon",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "cid=6685779~p=16~eid=00000187-dd9b-b68a-2019-d70a00e41030",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "8.1 kms",
    hasSurge: false,
    sla: {
      restaurantId: "614874",
      deliveryTime: 30,
      minDeliveryTime: 30,
      maxDeliveryTime: 30,
      lastMileTravel: 8.100000381469727,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: true,
    avgRating: "4.6",
    totalRatings: 50,
    new: false,
  },

  {
    type: "F",
    id: "662723",
    name: "Cake Crunch",
    uuid: "3e43d207-fd63-4f32-9e63-3dd8f7c94472",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "Too Few Ratings",
    cloudinaryImageId: "8fe2116dae3e810d52b4afa743bc39ab",
    cuisines: ["Bakery", "Desserts"],
    tags: [],
    costForTwo: 100000,
    costForTwoString: "₹1000 FOR TWO",
    deliveryTime: 24,
    minDeliveryTime: 24,
    maxDeliveryTime: 24,
    slaString: "24 MINS",
    lastMileTravel: 0.6000000238418579,
    slugs: {
      restaurant: "cake-crunch-vaishali-nagar-vaishali-nagar",
      city: "jaipur",
    },
    cityState: "12",
    address:
      "The Learners Academy, 224-225, Engineers Colony,, Sirsi Rd, Panchyawala, Raghunath Vihar, Kanakpura, Jaipur, Rajasthan 302034, India",
    locality: "Sirsi Rd",
    parentId: 54837,
    unserviceable: false,
    veg: true,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "60% off",
      shortDescriptionList: [
        {
          meta: "60% off | Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "60% OFF",
      shortDescriptionList: [
        {
          meta: "Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "0.6 kms",
    hasSurge: false,
    sla: {
      restaurantId: "662723",
      deliveryTime: 24,
      minDeliveryTime: 24,
      maxDeliveryTime: 24,
      lastMileTravel: 0.6000000238418579,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "--",
    totalRatings: 0,
    new: false,
  },

  {
    type: "F",
    id: "698975",
    name: "Pizza Corner",
    uuid: "d92f4879-bb21-4b23-a7d0-cf8c536d861d",
    city: "12",
    area: "Vaishali Nagar",
    totalRatingsString: "Too Few Ratings",
    cloudinaryImageId: "",
    cuisines: ["Indian"],
    tags: [],
    costForTwo: 50000,
    costForTwoString: "₹500 FOR TWO",
    deliveryTime: 26,
    minDeliveryTime: 26,
    maxDeliveryTime: 26,
    slaString: "26 MINS",
    lastMileTravel: 0.5,
    slugs: {
      restaurant: "pizza-corner-vaishali-nagar-vaishali-nagar-2",
      city: "jaipur",
    },
    cityState: "12",
    address: "162 Engineer Colony Khatipura Road  Panchawala Jaipur",
    locality: "Engineer Colony",
    parentId: 158467,
    unserviceable: false,
    veg: false,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    aggregatedDiscountInfo: {
      header: "60% off",
      shortDescriptionList: [
        {
          meta: "60% off | Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    aggregatedDiscountInfoV2: {
      header: "60% OFF",
      shortDescriptionList: [
        {
          meta: "Use WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      descriptionList: [
        {
          meta: "60% off up to ₹100 | Use code WELCOMEBACK",
          discountType: "Percentage",
          operationType: "RESTAURANT",
        },
      ],
      subHeader: "",
      headerType: 0,
      superFreedel: "",
    },
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 2800,
          message: "",
        },
        {
          name: "time",
          fee: 2500,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5300,
      message: "",
      title: "Delivery Charge",
      amount: "5300",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "0.5 kms",
    hasSurge: false,
    sla: {
      restaurantId: "698975",
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      lastMileTravel: 0.5,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "--",
    totalRatings: 0,
    new: true,
  },
];

export { restaurantsData, imageBaseURL };
